fix(aws-s3): hotfix for AWS S3 endpoint
src/util/functions.ts:168:37 - error TS2339: Property 'endpoint' does not exist on type '{ region: string; access_key_id: string; secret_key: string; defaultBucketName: string; }'.

168           endpoint: config?.aws_s3?.endpoint || undefined,